name: Build container

#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
on:
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  #GH_REPO: ${{ github.repository }}                     # wiktorvip/...
  GH_REPONAME: ${{ github.event.repository.name }}      # ...
  #DOCKERHUB_REPO_NAME: "wiktorvip/..."
  #IMAGE_TAG: "1.0"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set varable APP_VERSION from file APP_VERSION if exist
      if: ${{ hashFiles('APP_VERSION') != '' }}
      run: APP_VER=$(cat APP_VERSION); echo "APP_VERSION=$APP_VER" >> ${GITHUB_ENV}

    - name: Set varable APP_VERSION to default if file not exist
      if: ${{ hashFiles('APP_VERSION') == '' }}
      run: echo "APP_VERSION=v1" >> ${GITHUB_ENV}

    - name: Lowercase the repo name and username
      run: echo "GH_REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: |
          ${{env.DOCKER_USERNAME}}/${{env.GH_REPONAME}}:${{github.run_number}}
          ${{env.DOCKER_USERNAME}}/${{env.GH_REPONAME}}:latest
          ${{env.DOCKER_USERNAME}}/${{env.GH_REPONAME}}:${{env.APP_VERSION}}

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{env.DOCKER_USERNAME}}
        password: ${{env.DOCKER_PASSWORD}}
        repository: ${{env.GH_REPO}}
        short-description: ${{ github.event.repository.description }}

    - name: Push image to GHCR
      run: |
        docker buildx imagetools create \
          --tag ghcr.io/${{env.GH_REPO}}:latest \
          --tag ghcr.io/${{env.GH_REPO}}:${{github.run_number}} \
          --tag ghcr.io/${{env.GH_REPO}}:${{env.APP_VERSION}} \
          ${{env.GH_REPO}}:latest
